---
apiVersion: v1
kind: Pod
metadata:
    name: vproapp
    labels:
       app: vproapp
spec:
    containers:
       - name: app
         image: imranvisualpath/freshtomapp
         ports:
          - name: vproapp-port
            containerPort: 8080 
